### ISSUE TITLE
Unresolved dependencies when building Stark

### ISSUE THREAD

**Issue by mithdrann** [dbis-ilm/stark#4]
Hi, thanks for this tool! 
I downloaded the zip file from GitHub and execute `sbt assembly` within Stark directory but I've got the attached Unresolved Dependencies error:

[StartBuildingError.txt](https://github.com/dbis-ilm/stark/files/1582781/StartBuildingError.txt)

It seems that set is searching `sbt-assembly` and `sbt-scoverage` with wrong Scala version (2.12) but I don't know how to solve this issue

**Comment by hag0r** [comment]
Hi, 
I pushed the lastest changes to this repository which removes the scoverage plugin and uses assembly 1.14.5 .

We're using sbt 1.0.3 . It should use Scala 2.11.8 and not 2.12, though. Not sure why it's looking for 2.12 versions... ?

Please let me know it builds now.

**Comment by mithdrann** [comment]
Hi,

I added your source code to my maven project, appended required dependencies to the pom.xml and compiled with maven from Eclipse IDE. It works fine for me.

Anyway, I tried to build your latest changes and `stark.jar` has been built fine.

Thank you very much.

**Comment by hag0r** [comment]
Ok, so it probably was just the wrong version of the assembly plugin.
